### PR TITLE
adds `beginend-define-mode` for `deft-mode`

### PR DESCRIPTION
**Pull request by FrancescElies**
Hi,

I would like to use `beginend` with [deft](https://github.com/jrblevin/deft).
Would you welcome this pr?

Best

### CODE REVIEW

**Comment by DamienCassou** [comment]
Thank you for your PR. Could you please try to remove the `(goto-char (point-max))` line? I think it's done automatically.

**Comment by DamienCassou** [comment]
Is it working the way you want?

**Comment by FrancescElies** [comment]
It does 👍 , thanks!

**Comment by DamienCassou** [comment]
Perfect. Good job.

**Pull request merged**
